---
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff-format
        name: ‚òïÔ∏è Format using ruff
      - id: ruff
        name: ‚úÖ Lint using ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: codespell
        name: ‚úÖ Check code for common misspellings
        language: system
        types: [text]
        exclude: |
          (?x)^(
              .lock|
              CHANGELOG.md
          )$
        entry: uv run codespell --ignore-words=.codespell
      - id: mypy
        name: üÜé Static type checking using mypy
        language: system
        types: [python]
        entry: uv run mypy
        require_serial: true
      - id: yamllint
        name: üéó  Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: uv run yamllint
      - id: pytest
        name: üß™ Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: uv run pytest
        pass_filenames: false

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.10.0"
    hooks:
      - id: shellcheck
        name: ‚úÖ Check Shell files
